# config/cameras.yaml
# Camera configurations for Vision Engine

cameras:
  cam_01:
    name: "Trang Phục biểu diễn Phương Trần Đà Nẵng"
    youtube_url: "https://www.youtube.com/live/G_G8A6JU_LI?si=mR3WAJTQi8bnNBKk"
    frame_size: [1920, 1080]
    fps: 30
    roi:
      points:
        - [0, 615]
        - [1190, 265]
        - [1755, 275]
        - [1305, 1080]
        - [0, 1080]
    
    perspective:
      src_points: # hình chữ nhật nhỏ nhất bao quanh ROI
        - [0, 1080]
        - [0, 265]
        - [1755, 265]
        - [1755, 1080]
      dst_points: # góc nhìn BEV để tính toán tốc độ chính xác hơn (đảm bảo tỷ lệ thực tế giữa x và y)
        - [250, 650]
        - [250, 50]
        - [550, 50]
        - [550, 650]
      output_size: [800, 600]
      # Tỷ lệ thực tế (m) trên mỗi pixel sau khi chuyển đổi phối cảnh tương ứng với output_size của cam_01
      meters_per_pixel_x: 0.055
      meters_per_pixel_y: 0.060
    

  cam_02:
    name: "Camera cổng trường Nguyễn Huệ Đà Nẵng"
    youtube_url: "https://www.youtube.com/live/sJvEFrG0wq0?si=NZ_Wg-WZ3KR2VskB"
    frame_size: [1920, 1080]
    fps: 30
    roi:
      points:
        - [0, 625]
        - [860, 300]
        - [1220, 305]
        - [650, 1080]

    perspective:
      src_points: # HÌNH CHỮ NHẬT nhỏ nhất bao quanh ROI
        - [0, 1080]
        - [0, 300]
        - [1220, 300]
        - [1220, 1080]
      dst_points: # tương ứng với src nhưng tạo thành hình chữ nhật đều
        - [250, 650]
        - [250, 50]
        - [550, 50]
        - [550, 650]

      output_size: [800, 600]
      # Tỷ lệ thực tế (m) trên mỗi pixel sau khi chuyển đổi phối cảnh tương ứng với output_size của cam_02
      meters_per_pixel_x: 0.060
      meters_per_pixel_y: 0.065

  cam_03:
    name: "Camera cổng Sau bệnh viện C Đà Nẵng"
    youtube_url: "https://www.youtube.com/live/oif_zZFIfB4?si=P18h_-jF5Snel9tj"
    frame_size: [1920, 1080]
    fps: 30
    roi:
      points:
        - [960, 1080]
        - [430, 320]
        - [745, 270]
        - [1920, 730]
    perspective:
      src_points: # HÌNH CHỮ NHẬT nhỏ nhất bao quanh ROI
        - [430, 1080]
        - [430, 270]
        - [1920, 270]
        - [1920, 1080]
      dst_points: # tương ứng với src nhưng tạo thành hình chữ nhật đều
        - [250, 650]
        - [250, 50]
        - [550, 50]
        - [550, 650]
      output_size: [800, 600]
      # Tỷ lệ thực tế (m) trên mỗi pixel sau khi chuyển đổi phối cảnh tương ứng với output_size của cam_03
      meters_per_pixel_x: 0.065
      meters_per_pixel_y: 0.070
