import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en-US' | 'en-GB' | 'vi-VN' | 'zh-CN' | 'ja-JP';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  'en-US': {
    'nav.dashboard': 'Dashboard',
    'nav.live-monitoring': 'Camera Feed',
    'nav.violations': 'Incident Log',
    'nav.vehicle-search': 'Vehicle Search',
    'nav.analytics': 'Analytics',
    'nav.map-center': 'Map Center',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.support': 'Support',
    'nav.copilot': 'AI Copilot',
    'nav.navigation': 'Navigation',
    'nav.control_matrix': 'Control Matrix',
    'topbar.search_placeholder': 'SYSTEM SEARCH...',
    'topbar.operator': 'OPERATOR',
    'topbar.unit': 'Unit 01 / SF',
    'topbar.precision_link': 'INITIALIZING PRECISION LINK...',
    'topbar.telemetry_error': 'TELEMETRY ERROR',
    'topbar.stationary': 'STATIONARY',
    'settings.title': 'System / Settings',
    'settings.subtitle': 'Configure network parameters and interface preferences',
    'settings.display_config': 'DISPLAY CONFIGURATION',
    'settings.display_subtitle': 'Interface Visual Parameters',
    'settings.visual_theme': 'Visual Theme',
    'settings.theme_desc': 'Select the primary interface color palette',
    'settings.grid_density': 'Grid Density',
    'settings.grid_desc': 'Adjust the information density of data panels',
    'settings.lang_selection': 'Language Selection',
    'settings.lang_desc': 'Configure the system display language',
    'settings.security_title': 'SECURITY & PERMISSIONS',
    'settings.security_subtitle': 'Access Control Matrix',
    'settings.user_profile': 'USER PROFILE',
    'settings.identified_operator': 'Identified Operator',
    'settings.edit_profile': 'Edit Profile',
    'settings.sign_out': 'Terminal Sign Out',
    'settings.notifications': 'NOTIFICATIONS',
    'settings.alert_feed': 'Alert Feed Routing',
    'settings.system_alerts': 'System Alerts',
    'settings.save': 'Save Configurations',
    'dashboard.kpi.cameras': 'Cameras Online',
    'dashboard.kpi.offline': 'Offline Units',
    'dashboard.kpi.violations': 'Violations Today',
    'dashboard.kpi.incidents': 'Active Incidents',
    'dashboard.kpi.weather': 'Local Conditions',
    'dashboard.map_title': 'TACTICAL NETWORK OVERLAY',
    'dashboard.map_subtitle': 'Live Node Matrix',
    'dashboard.search_title': 'VEHICLE SEARCH',
    'dashboard.search_subtitle': 'Registry Lookup Utility',
    'dashboard.intersections_title': 'CRITICAL INTERSECTIONS',
    'dashboard.intersections_subtitle': 'Operational Status',
    'dashboard.violations_title': 'DETAILED VIOLATION REGISTRY',
    'dashboard.violations_subtitle': 'Infraction Monitor & Approval',
    'dashboard.events_title': 'EVENT STREAM',
    'dashboard.events_subtitle': 'Real-time Feed',
    'dashboard.table.intersection': 'Intersection / Node',
    'dashboard.table.load': 'Traffic Load',
    'dashboard.table.signal': 'Signal Status',
    'dashboard.table.efficiency': 'Efficiency',
    'dashboard.table.violations': 'Violations',
    'dashboard.table.enforcement': 'Enforcement Type',
    'dashboard.table.plate': 'Plate ID',
    'dashboard.table.site': 'Site Node',
    'dashboard.table.temporal': 'Temporal',
    'dashboard.table.status': 'Security Status',
    'dashboard.table.incidents': 'Incidents',
    'dashboard.search.plate': 'License Plate',
    'dashboard.search.vin': 'VIN Number',
    'dashboard.search.owner': 'Registered Owner',
    'dashboard.search.button': 'Execute Trace',
    'dashboard.ai.briefing': 'NEURAL STORM BRIEFING',
    'dashboard.ai.initializing': 'INITIALIZING TACTICAL DATA STREAM...',
    'dashboard.ai.model': 'MODEL',
    'dashboard.ai.priority': 'PRIORITY',
    'dashboard.ai.high_tactical': 'HIGH TACTICAL',
    'dashboard.ai.analyzing': 'ANALYZING...',
    'dashboard.ai.refresh': 'REFRESH LINK',
    'dashboard.ai.command_intel': 'COMMAND INTELLIGENCE',
    'dashboard.ai.neural_link': 'GEMINI NEURAL LINK',
    'status.active': 'Active',
    'status.nominal': 'Nominal',
    'status.congested': 'Congested',
    'status.offline': 'Offline',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.pending': 'Pending',
    'status.critical': 'Critical',
    'status.elevated': 'Elevated',
    'status.normal': 'Normal',
    'status.cleared': 'Cleared',
    'status.flagged': 'Flagged',
    'status.stolen': 'Stolen',
    'settings.grid.standard': 'Standard (Def)',
    'settings.grid.compact': 'High Density',
    'settings.grid.comfortable': 'Expanded',
    'map.filter.critical': 'Critical',
    'map.filter.elevated': 'Elevated',
    'map.filter.normal': 'Normal',
    'map.nav_mode': 'NAV MODE',
    'map.zoom': 'ZOOM',
    'map.reset': 'Reset View',
    'dashboard.search_history': 'Search History',
    'dashboard.ai.title': 'Intelligence',
    'dashboard.ai.ops_center': 'Operations Center',
    'dashboard.ai.neural_insights': 'Neural Insights',
    'dashboard.ai.query_placeholder': 'QUERY SYSTEM...',
    'dashboard.ai.path_opt': 'PATH OPTIMIZATION',
    'dashboard.ai.temporal_comp': 'TEMPORAL COMPARISON',
    'dashboard.ai.manifest_gen': 'MANIFEST GENERATOR',
    'dashboard.incident.summarize': 'AI Summary',
    'dashboard.incident.summarizing': 'Summarizing...',
    'dashboard.incident.summary': 'System Summary',
    'vehicle.neural_identity': 'NEURAL IDENTITY',
    'vehicle.registry_cross': 'REGISTRY CROSS REFERENCE',
    'vehicle.db_status': 'DB STATUS',
    'vehicle.synchronized': 'SYNCHRONIZED',
    'vehicle.records_online': 'RECORDS ONLINE',
    'vehicle.query_params': 'QUERY PARAMS',
    'vehicle.neural_filters': 'NEURAL FILTERS',
    'vehicle.plate_number': 'PLATE NUMBER',
    'vehicle.vin_number': 'VIN NUMBER',
    'vehicle.type': 'VEHICLE TYPE',
    'vehicle.color_match': 'NEURAL COLOR MATCH',
    'vehicle.execute_search': 'EXECUTE SEARCH',
    'vehicle.scanning': 'SCANNING...',
    'vehicle.recent_logs': 'RECENT NEURAL LOGS',
    'vehicle.neural_history': 'NEURAL HISTORY',
    'vehicle.flush_cache': 'FLUSH CACHE',
    'vehicle.no_logs': 'NO LOGS IN LOCAL BUFFER',
    'vehicle.registry_results': 'REGISTRY RESULTS',
    'vehicle.matches': 'MATCHES',
    'vehicle.optimizing': 'OPTIMIZING NEURAL WEIGHTS...',
    'vehicle.accessing_db': 'ACCESSING NODE DATABASE',
    'vehicle.no_matches': 'NO MATCHING RECORDS FOUND IN NEURAL REGISTRY',
    'vehicle.manufacturer': 'MANUFACTURER',
    'vehicle.visual_spec': 'VISUAL SPEC',
    'vehicle.last_telemetric': 'LAST TELEMETRIC',
    'vehicle.predictive_analysis': 'PREDICTIVE ANALYSIS',
    'analytics.neural_metrics': 'NEURAL METRICS',
    'analytics.op_intel': 'OPERATIONAL INTELLIGENCE',
    'analytics.network_load': 'NETWORK LOAD',
    'analytics.avg_velocity': 'AVG VELOCITY',
    'analytics.traffic_density': 'TRAFFIC DENSITY',
    'analytics.incident_rate': 'INCIDENT RATE',
    'analytics.system_latency': 'SYSTEM LATENCY',
    'analytics.network_volume': 'NETWORK VOLUME',
    'analytics.temporal_dist': 'TEMPORAL DISTRIBUTION',
    'analytics.vehicle_mix': 'VEHICLE MIX',
    'analytics.classification': 'NEURAL CLASSIFICATION',
    'analytics.predictive_models': 'PREDICTIVE MODELS',
    'analytics.synthetic_forecasts': 'HISTORICAL VS SYNTHETIC FORECASTS',
    'placeholder.secure_net': 'SECURE NETWORK PROT',
    'placeholder.node_id': 'NODE ID',
    'placeholder.system_status': 'SYSTEM STATUS',
    'placeholder.diagnostic': 'REAL-TIME MODULE DIAGNOSTIC',
    'placeholder.initialization': 'INITIALIZATION',
    'placeholder.standby': 'PLEASE STANDBY FOR SECURE DATA HANDSHAKE',
    'incident.log_protocol': 'LOG PROTOCOL',
    'incident.central_archive': 'CENTRAL ARCHIVE',
    'incident.access_secure': 'ACCESS LEVEL: SECURE',
    'incident.export_manifest': 'EXPORT MANIFEST',
    'incident.encrypted_conn': 'Encrypted Connection',
    'incident.search_placeholder': 'SEARCH BY ID OR LOCATION...',
    'incident.filter_critical': 'CRITICAL',
    'incident.filter_recent': 'RECENT',
    'incident.filter_node': 'NODE SELECT',
    'incident.event_history': 'EVENT HISTORY',
    'incident.audit_trail': 'Full Audit Trail',
    'incident.sync_archive': 'Synchronizing Archive Data...',
    'incident.table.id': 'Tracking ID',
    'incident.table.type': 'Event Type',
    'incident.table.location': 'Location Node',
    'incident.table.timestamp': 'Timestamp',
    'incident.table.operator': 'Operator',
    'incident.table.status': 'Status',
    'incident.no_records': 'No matching records found in secure archive.',
    'incident.page': 'Page',
    'monitor.stream_overlay': 'STREAM OVERLAY',
    'monitor.node_cluster': 'NODE CLUSTER ZETA',
    'monitor.encrypted_feed': 'ENCRYPTED FEED',
    'monitor.system_health': 'System Health',
    'monitor.primary_feed': 'PRIMARY FEED',
    'monitor.thermal_res': 'NODE W11 // HIGH RES THERMAL',
    'monitor.node_stream': 'NODE STREAM',
    'monitor.telemetry': 'TELEMETRY',
    'monitor.signal_strength': 'Signal Strength / Hubs',
    'monitor.rescan': 'RESCAN CLUSTER',
    'monitor.auto_analysis': 'AUTO ANALYSIS',
    'monitor.motion_vectoring': 'Motion Vectoring',
    'monitor.engine_active': 'Detection Engine Active',
    'monitor.cpu_util': 'CPU UTIL',
    'monitor.pattern_anomalies': 'Analyzing Westside Cluster for pattern anomalies. Currently tracking 1,244 moving entities across primary grids.',
    'monitor.stream_live': 'LIVE STREAMING',
    'monitor.zoom_out': 'ZOOM-OUT',
    'monitor.zoom_in': 'ZOOM-IN',
    'monitor.secure_aes': 'SECURE STREAM ENCRYPTED AES256',
    'map.geospatial_core': 'GEOSPATIAL CORE',
    'map.telemetry_link': 'LIVE TELEMETRY LINK',
    'map.coord_jump': 'COORD JUMP...',
    'map.layer_stack': 'LAYER STACK',
    'map.active_overlays': 'Active Overlays',
    'map.region_select': 'REGION SELECT',
    'map.zone_isolation': 'Zone Isolation',
    'map.render_mode': 'RENDER MODE: TACTICAL LIVE',
    'map.precision': 'PRECISION',
    'map.velocity': 'VELOCITY',
    'map.heading': 'HEADING',
    'map.assets_online': 'ASSETS ONLINE',
    'map.active_alerts': 'ACTIVE ALERTS',
    'map.grid_sync': 'GRID SYNC',
    'map.initializing_handshake': 'Initializing regional handshake...',
    'map.secure_vector': 'Secure Vector Rendering Engine',
    'map.layer.traffic_flow': 'Traffic Flow Density',
    'map.layer.public_transit': 'Public Transit Node',
    'map.layer.incident_hotspots': 'Incident Hotspots',
    'map.layer.asset_tracking': 'Asset Tracking',
    'reports.manifest_archive': 'MANIFEST ARCHIVE',
    'reports.sync_export': 'SYNCHRONIZED EXPORT UTILITY',
    'reports.integrity_verified': 'Integrity Verified',
    'reports.generator': 'REPORT GENERATOR',
    'reports.config_manifest': 'Configuration Manifest',
    'reports.template': 'Report Template',
    'reports.temporal_range': 'Temporal Range',
    'reports.from': 'FROM',
    'reports.to': 'TO',
    'reports.output_params': 'Output Parameters',
    'reports.compile': 'COMPILE REPORT',
    'reports.data_export': 'DATA EXPORT',
    'reports.db_dump': 'Direct Database Dump',
    'reports.db_request': 'Request full PostgreSQL dump for external BI processing. Access logs will be generated.',
    'reports.db_access': 'Request DB Access',
    'reports.archives': 'REPORT ARCHIVES',
    'reports.secure_repo': 'Secure File Repository',
    'reports.filter_name': 'FILTER BY NAME...',
    'reports.sort_date': 'Sort By Date',
    'reports.verified': 'VERIFIED',
    'reports.view_all': 'View All Archived Manifests',
    'reports.sync_status': 'Sync Status',
    'reports.primary': 'PRIMARY',
    'reports.secondary': 'SECONDARY',
    'reports.neural': 'NEURAL',
    'reports.template_full': 'Full Network Audit',
    'reports.template_incident': 'Incident Frequency Map',
    'reports.template_velocity': 'Velocity Delta Analysis',
    'reports.template_asset': 'Asset Deployment Log',
    'reports.param_raw': 'Include Sensor Raw Data',
    'reports.param_neural': 'Neural Insight Appendum',
    'reports.param_relational': 'Relational Graph Export',
  },
  'en-GB': {
    'nav.dashboard': 'Dashboard',
    'nav.live-monitoring': 'Camera Feed',
    'nav.violations': 'Incident Log',
    'nav.vehicle-search': 'Vehicle Search',
    'nav.analytics': 'Analytics',
    'nav.map-center': 'Map Center',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.support': 'Support',
    'nav.copilot': 'AI Copilot',
    'nav.navigation': 'Navigation',
    'nav.control_matrix': 'Control Matrix',
    'topbar.search_placeholder': 'SYSTEM SEARCH...',
    'topbar.operator': 'OPERATOR',
    'topbar.unit': 'Unit 01 / LDN',
    'settings.title': 'System / Settings',
    'settings.subtitle': 'Configure network parameters and interface preferences',
    'settings.display_config': 'DISPLAY CONFIGURATION',
    'settings.display_subtitle': 'Interface Visual Parameters',
    'settings.visual_theme': 'Visual Theme',
    'settings.theme_desc': 'Select the primary interface colour palette',
    'settings.grid_density': 'Grid Density',
    'settings.grid_desc': 'Adjust the information density of data panels',
    'settings.lang_selection': 'Language Selection',
    'settings.lang_desc': 'Configure the system display language',
    'settings.security_title': 'SECURITY & PERMISSIONS',
    'settings.security_subtitle': 'Access Control Matrix',
    'settings.user_profile': 'USER PROFILE',
    'settings.identified_operator': 'Identified Operator',
    'settings.edit_profile': 'Edit Profile',
    'settings.sign_out': 'Terminal Sign Out',
    'settings.notifications': 'NOTIFICATIONS',
    'settings.alert_feed': 'Alert Feed Routing',
    'settings.system_alerts': 'System Alerts',
    'settings.save': 'Save Configurations',
    'dashboard.kpi.cameras': 'Cameras Online',
    'dashboard.kpi.offline': 'Offline Units',
    'dashboard.kpi.violations': 'Violations Today',
    'dashboard.kpi.incidents': 'Active Incidents',
    'dashboard.kpi.weather': 'Local Conditions',
    'dashboard.map_title': 'TACTICAL NETWORK OVERLAY',
    'dashboard.map_subtitle': 'Live Node Matrix',
    'dashboard.search_title': 'VEHICLE SEARCH',
    'dashboard.search_subtitle': 'Registry Lookup Utility',
    'dashboard.intersections_title': 'CRITICAL INTERSECTIONS',
    'dashboard.intersections_subtitle': 'Operational Status',
    'dashboard.violations_title': 'DETAILED VIOLATION REGISTRY',
    'dashboard.violations_subtitle': 'Infraction Monitor & Approval',
    'dashboard.events_title': 'EVENT STREAM',
    'dashboard.events_subtitle': 'Real-time Feed',
    'dashboard.table.intersection': 'Intersection / Node',
    'dashboard.table.load': 'Traffic Load',
    'dashboard.table.signal': 'Signal Status',
    'dashboard.table.efficiency': 'Efficiency',
    'dashboard.table.violations': 'Violations',
    'dashboard.table.enforcement': 'Enforcement Type',
    'dashboard.table.plate': 'Plate ID',
    'dashboard.table.site': 'Site Node',
    'dashboard.table.temporal': 'Temporal',
    'dashboard.table.status': 'Security Status',
    'dashboard.search.plate': 'License Plate',
    'dashboard.search.vin': 'VIN Number',
    'dashboard.search.owner': 'Registered Owner',
    'dashboard.search.button': 'Execute Trace',
    'status.active': 'Active',
    'status.nominal': 'Nominal',
    'status.congested': 'Congested',
    'status.offline': 'Offline',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.pending': 'Pending',
    'settings.grid.standard': 'Standard (Def)',
    'settings.grid.compact': 'High Density',
    'settings.grid.comfortable': 'Expanded',
    'map.filter.critical': 'Critical',
    'map.filter.elevated': 'Elevated',
    'map.filter.normal': 'Normal',
    'map.nav_mode': 'NAV MODE',
    'map.zoom': 'ZOOM',
    'map.reset': 'Reset View',
    'dashboard.search_history': 'Search History',
    'dashboard.ai.title': 'Intelligence',
    'dashboard.ai.ops_center': 'Operations Center',
    'dashboard.ai.neural_insights': 'Neural Insights',
    'dashboard.ai.query_placeholder': 'QUERY SYSTEM...',
    'dashboard.ai.path_opt': 'PATH OPTIMIZATION',
    'dashboard.ai.temporal_comp': 'TEMPORAL COMPARISON',
    'dashboard.ai.manifest_gen': 'MANIFEST GENERATOR',
    'dashboard.incident.summarize': 'AI Summary',
    'dashboard.incident.summarizing': 'Summarising...',
    'dashboard.incident.summary': 'System Summary',
  },
  'vi-VN': {
    'nav.dashboard': 'Bảng Điều Khiển',
    'nav.live-monitoring': 'Nguồn Camera',
    'nav.violations': 'Nhật Ký Sự Cố',
    'nav.vehicle-search': 'Tìm Kiếm Xe',
    'nav.analytics': 'Phân Tích',
    'nav.map-center': 'Trung Tâm Bản Đồ',
    'nav.reports': 'Báo Cáo',
    'nav.settings': 'Cài Đặt',
    'nav.support': 'Hỗ Trợ',
    'nav.copilot': 'AI Copilot',
    'nav.navigation': 'Điều Hướng',
    'nav.control_matrix': 'Ma Trận Điều Khiển',
    'topbar.search_placeholder': 'TÌM KIẾM HỆ THỐNG...',
    'topbar.operator': 'NHÂN VIÊN',
    'topbar.unit': 'Đơn vị 01 / HN',
    'topbar.precision_link': 'ĐANG KHỞI TẠO LIÊN KẾT CHÍNH XÁC...',
    'topbar.telemetry_error': 'LỖI ĐO LƯỜNG TỪ XA',
    'topbar.stationary': 'ĐANG ĐỨNG YÊN',
    'settings.title': 'Hệ thống / Cài đặt',
    'settings.subtitle': 'Cấu hình thông số mạng và sở thích giao diện',
    'settings.display_config': 'CẤU HÌNH HIỂN THỊ',
    'settings.display_subtitle': 'Thông Số Thị Giác Giao Diện',
    'settings.visual_theme': 'Chủ Đề Thị Giác',
    'settings.theme_desc': 'Chọn bảng màu giao diện chính',
    'settings.grid_density': 'Mật Độ Lưới',
    'settings.grid_desc': 'Điều chỉnh mật độ thông tin của các bảng dữ liệu',
    'settings.lang_selection': 'Lựa Chọn Ngôn Ngữ',
    'settings.lang_desc': 'Cấu hình ngôn ngữ hiển thị hệ thống',
    'settings.security_title': 'BẢO MẬT & QUYỀN HẠN',
    'settings.security_subtitle': 'Ma Trận Kiểm Soát Truy Cập',
    'settings.user_profile': 'HỒ SƠ NGƯỜI DÙNG',
    'settings.identified_operator': 'Nhân Viên Được Xác Định',
    'settings.edit_profile': 'Chỉnh Sửa Hồ Sơ',
    'settings.sign_out': 'Đăng Xuất Thiết Bị',
    'settings.notifications': 'THÔNG BÁO',
    'settings.alert_feed': 'Định Tuyến Nguồn Cấp Cảnh Báo',
    'settings.system_alerts': 'Cảnh Báo Hệ Thống',
    'settings.save': 'Lưu Cấu Hình',
    'dashboard.kpi.cameras': 'Camera Trực Tuyến',
    'dashboard.kpi.offline': 'Đơn Vị Ngoại Tuyến',
    'dashboard.kpi.violations': 'Vi Phạm Hôm Nay',
    'dashboard.kpi.incidents': 'Sự Cố Đang Hoạt Động',
    'dashboard.kpi.weather': 'Điều Kiện Địa Phương',
    'dashboard.map_title': 'LỚP PHỦ MẠNG CHIẾN THUẬT',
    'dashboard.map_subtitle': 'Ma Trận Nút Trực Tiếp',
    'dashboard.search_title': 'TÌM KIẾM PHƯƠNG TIỆN',
    'dashboard.search_subtitle': 'Tiện Ích Tra Cứu Đăng Ký',
    'dashboard.intersections_title': 'GIAO LỘ TRỌNG YẾU',
    'dashboard.intersections_subtitle': 'Trạng Thái Vận Hành',
    'dashboard.violations_title': 'SỔ ĐĂNG KÝ VI PHẠM CHI TIẾT',
    'dashboard.violations_subtitle': 'Giám Sát & Phê Duyệt Vi Phạm',
    'dashboard.events_title': 'DÒNG SỰ KIỆN',
    'dashboard.events_subtitle': 'Nguồn Cấp Phút Thực',
    'dashboard.table.intersection': 'Giao Lộ / Nút',
    'dashboard.table.load': 'Lưu Lượng',
    'dashboard.table.signal': 'Trạng Thái Tín Hiệu',
    'dashboard.table.efficiency': 'Hiệu Suất',
    'dashboard.table.violations': 'Vi Phạm',
    'dashboard.table.enforcement': 'Loại Thực Thi',
    'dashboard.table.plate': 'Mã Biển Số',
    'dashboard.table.site': 'Nút Địa Điểm',
    'dashboard.table.temporal': 'Thời Gian',
    'dashboard.table.status': 'Trạng Thái Bảo Mật',
    'dashboard.table.incidents': 'Sự Cố',
    'dashboard.search.plate': 'Biển Số Xe',
    'dashboard.search.vin': 'Số Khung (VIN)',
    'dashboard.search.owner': 'Chủ Sở Hữu Đăng Ký',
    'dashboard.search.button': 'Thực Hiện Truy Vết',
    'dashboard.ai.briefing': 'BẢN TIN BÃO THẦN KINH',
    'dashboard.ai.initializing': 'ĐANG KHỞI TẠO DÒNG DỮ LIỆU CHIẾN THUẬT...',
    'dashboard.ai.model': 'MÔ HÌNH',
    'dashboard.ai.priority': 'ƯU TIÊN',
    'dashboard.ai.high_tactical': 'CHIẾN THUẬT CAO',
    'dashboard.ai.analyzing': 'ĐANG PHÂN TÍCH...',
    'dashboard.ai.refresh': 'LÀM MỚI LIÊN KẾT',
    'dashboard.ai.command_intel': 'TRÍ TUỆ CHỈ HUY',
    'dashboard.ai.neural_link': 'LIÊN KẾT THẦN KINH GEMINI',
    'status.active': 'Hoạt Động',
    'status.nominal': 'Bình Thường',
    'status.congested': 'Tắc Nghẽn',
    'status.offline': 'Ngoại Tuyến',
    'status.approved': 'Đã Phê Duyệt',
    'status.rejected': 'Đã Từ Chối',
    'status.pending': 'Đang Chờ',
    'status.critical': 'Nguy Cấp',
    'status.elevated': 'Cảnh Báo',
    'status.normal': 'Bình Thường',
    'status.cleared': 'Đã Xóa',
    'status.flagged': 'Đã Đánh Dấu',
    'status.stolen': 'Đã Bất Trộm',
    'settings.grid.standard': 'Tiêu Chuẩn',
    'settings.grid.compact': 'Mật Độ Cao',
    'settings.grid.comfortable': 'Mở Rộng',
    'map.filter.critical': 'Nguy Cấp',
    'map.filter.elevated': 'Cảnh Báo',
    'map.filter.normal': 'Bình Thường',
    'map.nav_mode': 'CHẾ ĐỘ NAV',
    'map.zoom': 'THU PHÓNG',
    'map.reset': 'Đặt Lại Chế Độ Xem',
    'dashboard.search_history': 'Lịch Sử Tìm Kiếm',
    'dashboard.ai.title': 'Trí Tuệ Nhân Tạo',
    'dashboard.ai.ops_center': 'Trung Tâm Vận Hành',
    'dashboard.ai.neural_insights': 'Thông Tin Chi Tiết Hệ Thần Kinh',
    'dashboard.ai.query_placeholder': 'TRUY VẤN HỆ THỐNG...',
    'dashboard.ai.path_opt': 'TỐI ƯU HÓA LỘ TRÌNH',
    'dashboard.ai.temporal_comp': 'SO SÁNH THỜI GIAN',
    'dashboard.ai.manifest_gen': 'MÁY TẠO BẢN KÊ',
    'dashboard.incident.summarize': 'Tóm tắt AI',
    'dashboard.incident.summarizing': 'Đang tóm tắt...',
    'dashboard.incident.summary': 'Bản tóm tắt hệ thống',
    'vehicle.neural_identity': 'DANH TÍNH THẦN KINH',
    'vehicle.registry_cross': 'TRA CỨU CHÉO ĐĂNG KÝ',
    'vehicle.db_status': 'TRẠNG THÁI CSDL',
    'vehicle.synchronized': 'ĐÃ ĐỒNG BỘ HÓA',
    'vehicle.records_online': 'BẢN GHI TRỰC TUYẾN',
    'vehicle.query_params': 'THAM SỐ TRUY VẤN',
    'vehicle.neural_filters': 'BỘ LỌC THẦN KINH',
    'vehicle.plate_number': 'BIỂN SỐ XE',
    'vehicle.vin_number': 'SỐ KHUNG (VIN)',
    'vehicle.type': 'LOẠI PHƯƠNG TIỆN',
    'vehicle.color_match': 'KHỚP MÀU THẦN KINH',
    'vehicle.execute_search': 'THỰC HIỆN TÌM KIẾM',
    'vehicle.scanning': 'ĐANG QUÉT...',
    'vehicle.recent_logs': 'NHẬT KÝ THẦN KINH GẦN ĐÂY',
    'vehicle.neural_history': 'LỊCH SỬ THẦN KINH',
    'vehicle.flush_cache': 'XÓA BỘ NHỚ ĐỆM',
    'vehicle.no_logs': 'KHÔNG CÓ NHẬT KÝ TRONG BỘ NHỚ CỤC BỘ',
    'vehicle.registry_results': 'KẾT QUẢ ĐĂNG KÝ',
    'vehicle.matches': 'KHỚP',
    'vehicle.optimizing': 'TỐI ƯU HÓA TRỌNG SỐ THẦN KINH...',
    'vehicle.accessing_db': 'TRUY CẬP CƠ SỞ DỮ LIỆU NÚT',
    'vehicle.no_matches': 'KHÔNG TÌM THẤY BẢN GHI PHÙ HỢP TRONG ĐĂNG KÝ THẦN KINH',
    'vehicle.manufacturer': 'NHÀ SẢN XUẤT',
    'vehicle.visual_spec': 'THÔNG SỐ THỊ GIÁC',
    'vehicle.last_telemetric': 'PHÉP ĐO TỪ XA CUỐI CÙNG',
    'vehicle.predictive_analysis': 'PHÂN TÍCH DỰ ĐOÁN',
    'analytics.neural_metrics': 'CHỈ SỐ THẦN KINH',
    'analytics.op_intel': 'TRÍ TUỆ VẬN HÀNH',
    'analytics.network_load': 'TẢI MẠNG',
    'analytics.avg_velocity': 'VẬN TỐC TRUNG BÌNH',
    'analytics.traffic_density': 'MẬT ĐỘ GIAO THÔNG',
    'analytics.incident_rate': 'TỶ LỆ SỰ CỐ',
    'analytics.system_latency': 'ĐỘ TRỄ HỆ THỐNG',
    'analytics.network_volume': 'LƯU LƯỢNG MẠNG',
    'analytics.temporal_dist': 'PHÂN PHỐI THỜI GIAN',
    'analytics.vehicle_mix': 'HỖN HỢP PHƯƠNG TIỆN',
    'analytics.classification': 'PHÂN LOẠI THẦN KINH',
    'analytics.predictive_models': 'MÔ HÌNH DỰ ĐOÁN',
    'analytics.synthetic_forecasts': 'DỰ BÁO LỊCH SỬ VS TỔNG HỢP',
    'placeholder.secure_net': 'GIAO THỨC MẠNG BẢO MẬT',
    'placeholder.node_id': 'MÃ NÚT',
    'placeholder.system_status': 'TRẠNG THÁI HỆ THỐNG',
    'placeholder.diagnostic': 'CHẨN ĐOÁN MÔ-ĐUN THỜI GIAN THỰC',
    'placeholder.initialization': 'KHỞI TẠO',
    'placeholder.standby': 'VUI LÒNG CHỜ BẮT TAY DỮ LIỆU BẢO MẬT',
    'incident.log_protocol': 'GIAO THỨC NHẬT KÝ',
    'incident.central_archive': 'KHO LƯU TRỮ TRUNG TÂM',
    'incident.access_secure': 'MỨC ĐỘ TRUY CẬP: BẢO MẬT',
    'incident.export_manifest': 'XUẤT BẢN KÊ',
    'incident.encrypted_conn': 'Kết Nối Được Mã Hóa',
    'incident.search_placeholder': 'TÌM KIẾM THEO ID HOẶC ĐỊA ĐIỂM...',
    'incident.filter_critical': 'NGUY CẤP',
    'incident.filter_recent': 'GẦN ĐÂY',
    'incident.filter_node': 'CHỌN NÚT',
    'incident.event_history': 'LỊCH SỬ SỰ KIỆN',
    'incident.audit_trail': 'Dấu Vết Kiểm Toán Đầy Đủ',
    'incident.sync_archive': 'Đang đồng bộ hóa dữ liệu lưu trữ...',
    'incident.table.id': 'Mã Theo Dõi',
    'incident.table.type': 'Loại Sự Kiện',
    'incident.table.location': 'Nút Địa Điểm',
    'incident.table.timestamp': 'Dấu Thời Gian',
    'incident.table.operator': 'Nhân Viên',
    'incident.table.status': 'Trạng Thái',
    'incident.no_records': 'Không tìm thấy bản ghi phù hợp trong kho lưu trữ bảo mật.',
    'incident.page': 'Trang',
    'monitor.stream_overlay': 'LỚP PHỦ DÒNG PHÁT',
    'monitor.node_cluster': 'CỤM NÚT ZETA',
    'monitor.encrypted_feed': 'NGUỒN CẤP ĐƯỢC MÃ HÓA',
    'monitor.system_health': 'Sức Khỏe Hệ Thống',
    'monitor.primary_feed': 'NGUỒN CẤP CHÍNH',
    'monitor.thermal_res': 'NÚT W11 // NHIỆT ĐỘ PHÂN GIẢI CAO',
    'monitor.node_stream': 'LUỒNG NÚT',
    'monitor.telemetry': 'ĐO LƯỜNG TỪ XA',
    'monitor.signal_strength': 'Cường Độ Tín Hiệu / Trung Tâm',
    'monitor.rescan': 'QUÉT LẠI CỤM',
    'monitor.auto_analysis': 'TỰ ĐỘNG PHÂN TÍCH',
    'monitor.motion_vectoring': 'Định Hướng Chuyển Động',
    'monitor.engine_active': 'Công Cụ Phát Hiện Đang Hoạt Động',
    'monitor.cpu_util': 'SỬ DỤNG CPU',
    'monitor.pattern_anomalies': 'Đang phân tích Cụm Westside để tìm các mẫu bất thường. Hiện đang theo dõi 1.244 thực thể đang chuyển động trên các lưới chính.',
    'monitor.stream_live': 'ĐANG PHÁT TRỰC TIẾP',
    'monitor.zoom_out': 'THU NHỎ',
    'monitor.zoom_in': 'PHÓNG TO',
    'monitor.secure_aes': 'LUỒNG BẢO MẬT ĐƯỢC MÃ HÓA AES256',
    'map.geospatial_core': 'LÕI ĐỊA KHÔNG GIAN',
    'map.telemetry_link': 'LIÊN KẾT ĐO LƯỜNG TRỰC TIẾP',
    'map.coord_jump': 'NHẢY TỌA ĐỘ...',
    'map.layer_stack': 'LỚP CHỒNG LỚP',
    'map.active_overlays': 'Lớp Phủ Đang Hoạt Động',
    'map.region_select': 'CHỌN KHU VỰC',
    'map.zone_isolation': 'Cách Ly Vùng',
    'map.render_mode': 'CHẾ ĐỘ KẾT XUẤT: CHIẾN THUẬT TRỰC TIẾP',
    'map.precision': 'ĐỘ CHÍNH XÁC',
    'map.velocity': 'VẬN TỐC',
    'map.heading': 'HƯỚNG ĐI',
    'map.assets_online': 'TÀI SẢN TRỰC TUYẾN',
    'map.active_alerts': 'CẢNH BÁO ĐANG HOẠT ĐỘNG',
    'map.grid_sync': 'ĐỒNG BỘ LƯỚI',
    'map.initializing_handshake': 'Đang khởi tạo bắt tay khu vực...',
    'map.secure_vector': 'Công cụ kết xuất vectơ bảo mật',
    'map.layer.traffic_flow': 'Mật Độ Lưu Lượng Giao Thông',
    'map.layer.public_transit': 'Nút Giao Thông Công Cộng',
    'map.layer.incident_hotspots': 'Điểm Nóng Sự Cố',
    'map.layer.asset_tracking': 'Theo Dõi Tài Sản',
    'map.layer.topographical': 'Địa Hình',
    'reports.manifest_archive': 'KHO LƯU TRỮ BẢN KÊ',
    'reports.sync_export': 'TIỆN ÍCH XUẤT ĐỒNG BỘ HÓA',
    'reports.integrity_verified': 'Đã Xác Minh Tính Toàn Vẹn',
    'reports.generator': 'TRÌNH TẠO BÁO CÁO',
    'reports.config_manifest': 'Bản Kê Cấu Hình',
    'reports.template': 'Mẫu Báo Cáo',
    'reports.temporal_range': 'Khoảng Thời Gian',
    'reports.from': 'TỪ',
    'reports.to': 'ĐẾN',
    'reports.output_params': 'Tham Số Đầu Ra',
    'reports.compile': 'BIÊN SOẠN BÁO CÁO',
    'reports.data_export': 'XUẤT DỮ LIỆU',
    'reports.db_dump': 'Bản Sao Lưu Cơ Sở Dữ Liệu Trực Tiếp',
    'reports.db_request': 'Yêu cầu bản sao lưu PostgreSQL đầy đủ để xử lý BI bên ngoài. Nhật ký truy cập sẽ được tạo.',
    'reports.db_access': 'Yêu Cầu Truy Cập DB',
    'reports.archives': 'KHO LƯU TRỮ BÁO CÁO',
    'reports.secure_repo': 'Kho Lưu Trữ Tệp Bảo Mật',
    'reports.filter_name': 'LỌC THEO TÊN...',
    'reports.sort_date': 'Sắp Xếp Theo Ngày',
    'reports.verified': 'ĐÃ XÁC MINH',
    'reports.view_all': 'Xem Tất Cả Các Bản Kê Đã Lưu Trữ',
    'reports.sync_status': 'Trạng Thái Đồng Bộ Hóa',
    'reports.primary': 'CHÍNH',
    'reports.secondary': 'PHỤ',
    'reports.neural': 'THẦN KINH',
    'reports.template_full': 'Kiểm Toán Toàn Bộ Mạng',
    'reports.template_incident': 'Bản Đồ Tần Suất Sự Cố',
    'reports.template_velocity': 'Phân Tích Chênh Lệch Vận Tốc',
    'reports.template_asset': 'Nhật Ký Triển Khai Tài Sản',
    'reports.param_raw': 'Bao Gồm Dữ Liệu Cảm Biến Thô',
    'reports.param_neural': 'Phụ Lục Thông Tin Thần Kinh',
    'reports.param_relational': 'Xuất Đồ Thị Liên Kết',
  },
  'zh-CN': {
    'nav.dashboard': '仪表板',
    'nav.live-monitoring': '摄像头馈送',
    'nav.violations': '事件日志',
    'nav.vehicle-search': '车辆查询',
    'nav.analytics': '分析',
    'nav.map-center': '地图中心',
    'nav.reports': '报告',
    'nav.settings': '设置',
    'nav.support': '支持',
    'nav.copilot': '人工智能',
    'nav.navigation': '导航',
    'nav.control_matrix': '控制矩阵',
    'topbar.search_placeholder': '系统搜索...',
    'topbar.operator': '操作员',
    'topbar.unit': '单元 01 / 北京',
    'settings.title': '系统 / 设置',
    'settings.subtitle': '配置网络参数和界面偏好',
    'settings.display_config': '显示配置',
    'settings.display_subtitle': '界面视觉参数',
    'settings.visual_theme': '视觉主题',
    'settings.theme_desc': '选择主要界面配色方案',
    'settings.grid_density': '网格密度',
    'settings.grid_desc': '调整数据面板的信息密度',
    'settings.lang_selection': '语言选择',
    'settings.lang_desc': '配置系统显示语言',
    'settings.security_title': '安全与权限',
    'settings.security_subtitle': '访问控制矩阵',
    'settings.user_profile': '用户资料',
    'settings.identified_operator': '已识别的操作员',
    'settings.edit_profile': '编辑资料',
    'settings.sign_out': '终端退出',
    'settings.notifications': '通知',
    'settings.alert_feed': '警报馈送路由',
    'settings.system_alerts': '系统警报',
    'settings.save': '保存配置',
    'dashboard.kpi.cameras': '在在线摄像头',
    'dashboard.kpi.offline': '离线单元',
    'dashboard.kpi.violations': '今日违规',
    'dashboard.kpi.incidents': '活跃事件',
    'dashboard.kpi.weather': '当地情况',
    'dashboard.map_title': '战术网络覆盖',
    'dashboard.map_subtitle': '实时节点矩阵',
    'dashboard.search_title': '车辆查询',
    'dashboard.search_subtitle': '注册查询工具',
    'dashboard.intersections_title': '关键交叉口',
    'dashboard.intersections_subtitle': '运行状态',
    'dashboard.violations_title': '详细违规登记',
    'dashboard.violations_subtitle': '违规监控与审批',
    'dashboard.events_title': '事件流',
    'dashboard.events_subtitle': '实时馈送',
    'dashboard.table.intersection': '交叉口 / 节点',
    'dashboard.table.load': '交通流量',
    'dashboard.table.signal': '信号状态',
    'dashboard.table.efficiency': '效率',
    'dashboard.table.violations': '违规',
    'dashboard.table.enforcement': '执法类型',
    'dashboard.table.plate': '车牌 ID',
    'dashboard.table.site': '站点节点',
    'dashboard.table.temporal': '时间',
    'dashboard.table.status': '安全状态',
    'dashboard.search.plate': '车牌号',
    'dashboard.search.vin': 'VIN 码',
    'dashboard.search.owner': '注册车主',
    'dashboard.search.button': '执行追踪',
    'status.active': '活跃',
    'status.nominal': '正常',
    'status.congested': '拥堵',
    'status.offline': '离线',
    'status.approved': '已批准',
    'status.rejected': '已拒绝',
    'status.pending': '待定',
    'settings.grid.standard': '标准 (默认)',
    'settings.grid.compact': '高密度',
    'settings.grid.comfortable': '扩展',
    'map.filter.critical': '关键',
    'map.filter.elevated': '升高',
    'map.filter.normal': '正常',
    'map.nav_mode': '导航模式',
    'map.zoom': '缩放',
    'map.reset': '重置视图',
    'dashboard.search_history': '搜索历史',
    'dashboard.ai.title': '智能',
    'dashboard.ai.ops_center': '运营中心',
    'dashboard.ai.neural_insights': '神经洞察',
    'dashboard.ai.query_placeholder': '查询系统...',
    'dashboard.ai.path_opt': '路径优化',
    'dashboard.ai.temporal_comp': '时间对比',
    'dashboard.ai.manifest_gen': '清单生成器',
    'dashboard.incident.summarize': 'AI 摘要',
    'dashboard.incident.summarizing': '正在摘要...',
    'dashboard.incident.summary': '系统摘要',
  },
  'ja-JP': {
    'nav.dashboard': 'ダッシュボード',
    'nav.live-monitoring': 'カメラフィード',
    'nav.violations': 'インシデントログ',
    'nav.vehicle-search': '車両検索',
    'nav.analytics': '分析',
    'nav.map-center': 'マップセンター',
    'nav.reports': 'レポート',
    'nav.settings': '設定',
    'nav.support': 'サポート',
    'nav.copilot': 'AIコパイロット',
    'nav.navigation': 'ナビゲーション',
    'nav.control_matrix': 'コントロールマトリックス',
    'topbar.search_placeholder': 'システム検索...',
    'topbar.operator': 'オペレーター',
    'topbar.unit': 'ユニット 01 / 東京',
    'settings.title': 'システム / 設定',
    'settings.subtitle': 'ネットワークパラメータとインターフェース設定を構成する',
    'settings.display_config': 'ディスプレイ構成',
    'settings.display_subtitle': 'インターフェース視覚パラメータ',
    'settings.visual_theme': '視覚テーマ',
    'settings.theme_desc': '主要なインターフェースカラーパレットを選択する',
    'settings.grid_density': 'グリッド密度',
    'settings.grid_desc': 'データパネルの情報密度を調整する',
    'settings.lang_selection': '言語選択',
    'settings.lang_desc': 'システム表示言語を構成する',
    'settings.security_title': 'セキュリティと権限',
    'settings.security_subtitle': 'アクセス制御マトリックス',
    'settings.user_profile': 'ユーザープロファイル',
    'settings.identified_operator': '特定されたオペレーター',
    'settings.edit_profile': 'プロファイルを編集',
    'settings.sign_out': 'ターミナルサインアウト',
    'settings.notifications': '通知',
    'settings.alert_feed': 'アラートフィードルーティング',
    'settings.system_alerts': 'システムアラート',
    'settings.save': '構成の保存',
    'dashboard.kpi.cameras': 'オンラインカメラ',
    'dashboard.kpi.offline': 'オフラインユニット',
    'dashboard.kpi.violations': '今日の違反',
    'dashboard.kpi.incidents': 'アクティブなインシデント',
    'dashboard.kpi.weather': '現地の状況',
    'dashboard.map_title': 'タクティカルネットワークオーバーレイ',
    'dashboard.map_subtitle': 'ライブノードマトリックス',
    'dashboard.search_title': '車両検索',
    'dashboard.search_subtitle': '登録ルックアップユーティリティ',
    'dashboard.intersections_title': '重要交差点',
    'dashboard.intersections_subtitle': '運用ステータス',
    'dashboard.violations_title': '詳細な違反レジストリ',
    'dashboard.violations_subtitle': '違反監視と承認',
    'dashboard.events_title': 'イベントストリーム',
    'dashboard.events_subtitle': 'リアルタイムフィード',
    'dashboard.table.intersection': '交差点 / ノード',
    'dashboard.table.load': '交通量',
    'dashboard.table.signal': '信号ステータス',
    'dashboard.table.efficiency': '効率',
    'dashboard.table.violations': '違反',
    'dashboard.table.enforcement': '執行タイプ',
    'dashboard.table.plate': 'ナンバープレート ID',
    'dashboard.table.site': 'サイトノード',
    'dashboard.table.temporal': '時間',
    'dashboard.table.status': 'セキュリティステータス',
    'dashboard.search.plate': '登録番号',
    'dashboard.search.vin': '車台番号 (VIN)',
    'dashboard.search.owner': '登録所有者',
    'dashboard.search.button': '追跡実行',
    'status.active': 'アクティブ',
    'status.nominal': '正常',
    'status.congested': '混雑',
    'status.offline': 'オフライン',
    'status.approved': '承認済み',
    'status.rejected': '却下',
    'status.pending': '保留中',
    'settings.grid.standard': '標準 (デフォルト)',
    'settings.grid.compact': '高密度',
    'settings.grid.comfortable': '拡張',
    'map.filter.critical': '重要',
    'map.filter.elevated': '上昇',
    'map.filter.normal': '正常',
    'map.nav_mode': 'ナビモード',
    'map.zoom': 'ズーム',
    'map.reset': '表示をリセット',
    'dashboard.search_history': '検索履歴',
    'dashboard.ai.title': 'インテリジェンス',
    'dashboard.ai.ops_center': 'オペレーションセンター',
    'dashboard.ai.neural_insights': 'ニューラルインサイト',
    'dashboard.ai.query_placeholder': 'システムクエリ...',
    'dashboard.ai.path_opt': '経路最適化',
    'dashboard.ai.temporal_comp': '時間比較',
    'dashboard.ai.manifest_gen': 'マニフェストジェネレーター',
    'dashboard.incident.summarize': 'AI 要約',
    'dashboard.incident.summarizing': '要約中...',
    'dashboard.incident.summary': 'システム要約',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en-US');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
